BlogWithMvc5/BlogWithMvc5/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BlogWithMvc5.Models
{
    public class Comment
    {

        public int Id { get; set; }
        [Required]
        public string makedComment { get; set; }

        [Editable(false)]
        public int ArticleID { get; set; }
    }
}

BlogWithMvc5/BlogWithMvc5/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogWithMvc5.Models;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace BlogWithMvc5.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin
        // GET: Visitor
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Index(int pageNumber = 1)
        {
            return View(db.Articles.OrderBy(x => x.date).ToList().ToPagedList(pageNumber, 10));
        }

        // GET: Admin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            ViewBag.Message = article.Subject;
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Subject,Author,Content,Picture,date")] Article article, HttpPostedFileBase photo)
        {
            //add picture
            if (photo != null && photo.ContentLength > 0)
            {

                var directory = (Server.MapPath("~/Content/image"));
                var fileName = Path.GetFileName(photo.FileName);
                ViewBag.Path = fileName;
                photo.SaveAs(Path.Combine(directory, fileName));

                article.Picture = fileName;

            }

            if (ModelState.IsValid)
            {
                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(article);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Subject,Author,Content,Picture,date")] Article article, HttpPostedFileBase photo)
        {

            if (photo != null && photo.ContentLength > 0)
            {

                var directory = (Server.MapPath("~/Content/image"));
                var fileName = Path.GetFileName(photo.FileName);
                //ViewBag.Path = fileName;
                photo.SaveAs(Path.Combine(directory, fileName));

                article.Picture = fileName;

            }

            if (ModelState.IsValid)
            {
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogWithMvc5/BlogWithMvc5/Controllers/VisitorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogWithMvc5.Models;
using PagedList;
using PagedList.Mvc;

namespace BlogWithMvc5.Controllers
{
    public class VisitorController : Controller
    {
        //Database Connection
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Visitor
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Index(int pageNumber = 1)
        {
            return View(db.Articles.OrderBy(x => x.date).ToList().ToPagedList(pageNumber, 10));
        }

        // GET: Visitor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            ViewBag.Message = article.Subject;
            if (article == null)
            {
                return HttpNotFound();
            }

            //var olan commentleri çektik articleId ye göre
            var comments = (from k in db.Comments
                            where k.ArticleID == id
                            select k.makedComment);

            ViewBag.articleComment = comments;


            return View(article);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [HttpPost]
        public string CommentsAdd(Comment comment)
        {
            if (!String.IsNullOrEmpty(comment.makedComment) && !String.IsNullOrEmpty(comment.ArticleID.ToString()))
            {

                comment.ArticleID = comment.ArticleID;
                comment.makedComment = comment.makedComment;

                db.Comments.Add(comment);
                db.SaveChanges();


                //TODO: Save the data in database
                return "Thank you " + comment.makedComment + ". Record Saved.";
            }
            else
                return "Please complete the form.";

        }


    }
}

BlogWithMvc5/BlogWithMvc5/Views/Shared/_BlogAdminName.cshtml
<p>
    Hoş geldiniz <b>Muhammed Safa BIÇAKCI - Blog</b>
    <br/>
   <span style="color:red"> Comment is avaliable only for Visitor</span>
</p>

BlogWithMvc5/BlogWithMvc5/Views/Shared/_CommentShowView.cshtml
@{
    ViewBag.articleComment = ViewData["comments"];
    ViewBag.Comment = "Comment : ";
}



@foreach (var item in ViewBag.articleComment)
{
    @ViewBag.Comment @item
    <br />
}

BlogWithMvc5/BlogWithMvc5/Views/Shared/_CommentView.cshtml
@{

    var id = ViewData["id"];
}

<div class="jumbotron">
    <h2>Comment</h2>

    <form id="formOfComment" action="/Visitor/CommentsAdd" method="post">
        <p>
            Enter your comment
           
            @* commenti almak için *@
            @Html.TextBox("comment.makedComment")

           
            @* Article Id almak için *@
            @Html.TextBox("comment.ArticleID", "" + @id, new { @style = "display:none" })


            <a href='@Url.Action("Details", "Visitor", new { id = id })'><input type="button" value="Save" id="Save" /></a>

            <span id="msg" style="color:red;" />

        </p>
    </form>



</div>

BlogWithMvc5/BlogWithMvc5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MyBlog</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Visitor", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home(Visitor)", "Index", "Visitor")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Admin Panel", "Index", "Admin")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        
        <div class="jumbotron">
            @Html.Partial("_BlogAdminName")
            @RenderBody()

        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MyBlog</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>